force-app/main/default/objects/Resident__c/Resident__c.object-meta.xml
<CustomObject>
    <label>Resident</label>
    <nameField>
        <label>Resident Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Residents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Resident__c/fields/Apartment__c.field-meta.xml
<CustomField>
    <fullName>Apartment__c</fullName>
    <label>Apartment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sai Vihar</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Resident__c/fields/Flat_Number__c.field-meta.xml
<CustomField>
    <fullName>Flat_Number__c</fullName>
    <label>Flat Number</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/ResidentController.cls
public class ResidentController {
    
    @auraEnabled
    public static list<Resident__c > getResident(Integer FlatNumber, String Phone){
        try{
            list<Resident__c > listResident =new list<Resident__c >();
            if(FlatNumber!=null && Phone!=null){
                listResident=[Select Id,Flat_Number__c, Phone__c, Name, Apartment__c, Active__c from Resident__c 
                              where Flat_Number__c=:FlatNumber AND Phone__c=:Phone];
                
            }
            return listResident;
        }
        catch(exception e){
            return null;
        }
    }
    
    @auraEnabled(cacheable=true)
    public static list<Resident__c > getAllResidents(){
        try{
            list<Resident__c > listResident =new list<Resident__c >();
            
            listResident=[Select Id,Flat_Number__c, Phone__c, Name, Apartment__c, Active__c,Email__c from Resident__c ];
            
            return listResident;
        }
        catch(exception e){
            return null;
        }
    }
}