force-app/main/default/objects/Asset__c/Asset__c.object-meta.xml
<CustomObject>
    <label>Asset</label>
    <nameField>
        <displayFormat>A-{000000}</displayFormat>
        <label>Asset ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Asset__c/fields/Asset_Price__c.field-meta.xml
<CustomField>
    <fullName>Asset_Price__c</fullName>
    <label>Asset Price</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Contribution__c/Contribution__c.object-meta.xml
<CustomObject>
    <label>Contribution</label>
    <nameField>
        <displayFormat>Contri-{0000000}</displayFormat>
        <label>Contribution ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contributions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Contribution__c/fields/Maintenance_Contribution__c.field-meta.xml
<CustomField>
    <fullName>Maintenance_Contribution__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Maintenance Contribution</label>
    <referenceTo>Maintenance_Contribution__c</referenceTo>
    <relationshipLabel>Contributions</relationshipLabel>
    <relationshipName>Contributions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contribution__c/fields/Payment_Status__c.field-meta.xml
<CustomField>
    <fullName>Payment_Status__c</fullName>
    <label>Payment Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Paid</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contribution__c/fields/Resident__c.field-meta.xml
<CustomField>
    <fullName>Resident__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Resident</label>
    <referenceTo>Resident__c</referenceTo>
    <relationshipLabel>Contributions</relationshipLabel>
    <relationshipName>Contributions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Maintenance_Contribution__c/Maintenance_Contribution__c.object-meta.xml
<CustomObject>
    <label>Maintenance Contribution</label>
    <nameField>
        <label>Maintenance Contribution Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Maintenance Contributions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Maintenance_Contribution__c/fields/Amount_Pending__c.field-meta.xml
<CustomField>
    <fullName>Amount_Pending__c</fullName>
    <formula>Amount__c - Amount_Received__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Amount Pending</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Maintenance_Contribution__c/fields/Asset__c.field-meta.xml
<CustomField>
    <fullName>Asset__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Asset</label>
    <referenceTo>Asset__c</referenceTo>
    <relationshipLabel>Maintenance Contributions</relationshipLabel>
    <relationshipName>Maintenance_Contributions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Maintenance_Contribution__c/fields/Contribution_Date__c.field-meta.xml
<CustomField>
    <fullName>Contribution_Date__c</fullName>
    <label>Contribution Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Maintenance_Contribution__c/fields/Maintenance_Request__c.field-meta.xml
<CustomField>
    <fullName>Maintenance_Request__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Related Maintenance Request</inlineHelpText>
    <label>Maintenance Request</label>
    <referenceTo>Maintenance_Request__c</referenceTo>
    <relationshipLabel>Maintenance Contributions</relationshipLabel>
    <relationshipName>Maintenance_Contributions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Maintenance_Contribution__c/fields/Resident__c.field-meta.xml
<CustomField>
    <fullName>Resident__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Resident who paid this contribution</label>
    <referenceTo>Resident__c</referenceTo>
    <relationshipLabel>Maintenance Contributions</relationshipLabel>
    <relationshipName>Maintenance_Contributions</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Maintenance_Contribution__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Due</fullName>
                <default>true</default>
                <label>Due</label>
            </value>
            <value>
                <fullName>Settled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Maintenance_Request__c/Maintenance_Request__c.object-meta.xml
<CustomObject>
    <label>Maintenance Request</label>
    <nameField>
        <label>Maintenance Request Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Maintenance Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Maintenance_Request__c/fields/Amount_Collected__c.field-meta.xml
<CustomField>
    <fullName>Amount_Collected__c</fullName>
    <defaultValue>0.00</defaultValue>
    <label>Amount Collected</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Maintenance_Request__c/fields/Amount_Pending__c.field-meta.xml
<CustomField>
    <fullName>Amount_Pending__c</fullName>
    <formula>Amount_Spent__c - Amount_Collected__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Amount Pending</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Maintenance_Request__c/fields/Amount_Spent__c.field-meta.xml
<CustomField>
    <fullName>Amount_Spent__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Amount Spent</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Maintenance_Request__c/fields/Assigned_Vendor__c.field-meta.xml
<CustomField>
    <fullName>Assigned_Vendor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assigned Vendor</label>
    <referenceTo>Vendor__c</referenceTo>
    <relationshipLabel>Maintenance Requests</relationshipLabel>
    <relationshipName>Maintenance_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Maintenance_Request__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Plumbing</fullName>
            </value>
            <value>
                <fullName>House Keeping</fullName>
            </value>
            <value>
                <fullName>Electrical</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Maintenance_Request__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <inlineHelpText>Add description of maintenance job</inlineHelpText>
    <label>Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Resident__c/Resident__c.object-meta.xml
<CustomObject>
    <label>Resident</label>
    <nameField>
        <label>Resident Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Residents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Resident__c/fields/Flat_Number__c.field-meta.xml
<CustomField>
    <fullName>Flat_Number__c</fullName>
    <label>Flat Number</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/MaintenanceContributionController.cls
public class MaintenanceContributionController {
    @auraEnabled(cacheable=true)
    public static list<Maintenance_Contribution__c> getMaintenanceContribution(String userId, String recordTypeName){
        try{
            String RecordTypeID = Schema.SObjectType.Maintenance_Contribution__c.getRecordTypeInfosByName().get(recordTypeName).getRecordTypeId();
            Map<Id,Maintenance_Contribution__c> mapMC= new Map<Id,Maintenance_Contribution__c>([Select id,Name, Amount__c,Amount_Pending__c, Amount_Received__c,Contribution_Date__c, Maintenance_Request__c,Maintenance_Request__r.name,Asset__c,Asset__r.Asset_Name__c,Asset__r.Asset_Price__c, Resident__c, (Select id, Name, Resident__c,Resident__r.name,Resident__r.Flat_Number__c, Amount__c,Contribution_Date__c, Maintenance_Contribution__c,Maintenance_Contribution__r.name, Payment_Status__c from Contributions__r where Payment_Status__c='Pending' order by amount__c desc)
                                                                                                from Maintenance_Contribution__c
                                                                                                Where Resident__c=:userId AND recordTypeId=:RecordTypeID]);
            
            list<Maintenance_Contribution__c> listMC =mapMC.values();
            set<Id> setMCIds= mapMC.keySet();
            
            return listMC;
        }
        catch(exception e){
            return null;
        }
    }
    
    @auraEnabled(cacheable=true)
    public static Decimal getRepaymentMaintenanceContribution(String userId){
        try{
            Decimal totalRepayment=0;
            Map<Id,Maintenance_Contribution__c> mapMC= new Map<Id,Maintenance_Contribution__c>([Select id,Name, Amount__c,Amount_Pending__c, Amount_Received__c,Contribution_Date__c, Maintenance_Request__c,Maintenance_Request__r.name, Resident__c
                                                                                                from Maintenance_Contribution__c
                                                                                                Where Resident__c=:userId]);
            if(!mapMC.isEmpty()){
                for(Maintenance_Contribution__c varMC:mapMC.values()){
                    totalRepayment=totalRepayment+varMC.Amount_Pending__c;
                }
            }
            
            return totalRepayment;
        }
        catch(exception e){
            return null;
        }
    }
    
    
    public static void updateRelatedMainReqAmount(list<Maintenance_Contribution__c> listMaintCont, Map<Id,Maintenance_Contribution__c> oldMap, Map<Id,Maintenance_Contribution__c>newMap){
        try{
            if(!newMap.isEmpty()){
                set<Id> maintReqIds = new set<Id>();
                String RecordTypeID = Schema.SObjectType.Maintenance_Contribution__c.getRecordTypeInfosByName().get('For Maintenance Request').getRecordTypeId();
                list<Maintenance_Request__c> listFinalMR = new list<Maintenance_Request__c>();
                for(Maintenance_Contribution__c varMC:newMap.values()){
                    maintReqIds.add(varMC.Maintenance_Request__c);
                }
                
                map<Id,Maintenance_Request__c> mapMR =new  map<Id,Maintenance_Request__c>([SELECT Id, Category__c,Description__c, Amount_Spent__c,Amount_Collected__c,Assigned_Vendor__c, Request_Date__c,Status__c,Priority__c 
                                                                                           from Maintenance_Request__c
                                                                                           Where ID IN:maintReqIds]);
                
                AggregateResult [] contriAggResult= [Select Maintenance_Request__c,SUM(Amount__c)AmountSpent, SUM(Amount_Received__c)CollectedAmount 
                                                     from Maintenance_Contribution__c 
                                                     Where Maintenance_Request__c IN :maintReqIds AND recordTypeId=:RecordTypeID
                                                     group by Maintenance_Request__c];
                
                if(!contriAggResult.isEmpty()){
                    for(AggregateResult varAgg:contriAggResult){
                        Maintenance_Request__c varMaintReq= mapMR.get((String)varAgg.get('Maintenance_Request__c'));
                        if(varMaintReq.Amount_Spent__c==0.00){
                            varMaintReq.Amount_Spent__c=(Decimal)varAgg.get('AmountSpent');
                        }
                        else if(varMaintReq.Amount_Spent__c!=0){
                            varMaintReq.Amount_Spent__c= varMaintReq.Amount_Spent__c+(Decimal)varAgg.get('AmountSpent');
                        }
                        varMaintReq.Amount_Collected__c=(Decimal)varAgg.get('CollectedAmount');
                        listFinalMR.add(varMaintReq);
                    }
                }
                if(!listFinalMR.isEmpty()){
                    Database.update(listFinalMR,false);
                }
            }
        }
        catch(exception e){
            
        }
    }
    
    
     @auraEnabled(cacheable=true)
    public static list<Maintenance_Contribution__c> getAllMaintenanceContribution(String userId){
        try{
           
            Map<Id,Maintenance_Contribution__c> mapMC= new Map<Id,Maintenance_Contribution__c>([Select Id,Name, Amount__c,Amount_Pending__c, Amount_Received__c,Contribution_Date__c, Maintenance_Request__c,Maintenance_Request__r.name,Asset__c,Asset__r.Asset_Name__c,Asset__r.Asset_Price__c, Resident__c
                                                                                                from Maintenance_Contribution__c
                                                                                                Where Resident__c=:userId]);
            
            list<Maintenance_Contribution__c> listMC =mapMC.values();
            set<Id> setMCIds= mapMC.keySet();
            
            return listMC;
        }
        catch(exception e){
            return null;
        }
    }
    
}